name = "r2-worker"
type = "javascript"

[env.production]
workers_dev = false
route = "r2-worker.jenericjakoby.workers.dev"  # Change this to your actual URL if you have one

[build]
command = "npm install"

[workers]
main = "cloudflare-worker.js"  # This is your worker script's filename

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "video-bucket"

[env.production.kv]
AUTH_KEY_SECRET = "goon"
